name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
          run: npm install


      - name: Build the Vite app
        run: npm run build

      - name: Deploy dist folder to hostinger-deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: hostinger-deploy
          folder: dist
          clean: true
          commit-message: "Auto build and deploy from GitHub Actions"
