name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # <-- This gives the Action permission to push code

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd vivid-site-shine-main
          npm install

      - name: Build Vite app
        run: |
          cd vivid-site-shine-main
          npm run build

      - name: Deploy built files to hostinger-deploy branch
        run: |
          cd vivid-site-shine-main/dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to Hostinger"
          git branch -M main
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main:hostinger-deploy
